name: Send publish metrics to bigquery
on:
  release:
    types: published
  push:
    branches: [ drstrangelove/release-metrics ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_BQ_METRICS_KEY }}
          export_default_credentials: true
      - run: cat $GITHUB_EVENT_PATH

      - run: |
          export HAS_RELEASE_KEY="$(jq 'has("release")' $GITHUB_EVENT_PATH)"
          echo "::set-env name=HAS_RELEASE_KEY::$HAS_RELEASE_KEY"

      - run: 'jq -c ''.release |
             {
               package_name: .name | split(" ")[0],
               name,
               tag_name,
               version: try(.tag_name | split("-v")[1]),
               html_url,
               target_commitish,
               created_at,
               published_at,
               draft,
               prerelease
             }'' $GITHUB_EVENT_PATH > releases.json'
        if: ${{env.HAS_RELEASE_KEY== 'true'}}

      - run: cat releases.json
        if: ${{env.HAS_RELEASE_KEY== 'true'}}

      - run: bq load --source_format=NEWLINE_DELIMITED_JSON metrics.releases releases.json
        if: ${{env.HAS_RELEASE_KEY== 'true'}}
